### ISSUE TITLE
Problem with container and keys set

### ISSUE THREAD

**Issue by panda87** [gcavalcante8808/docker-semaphore#1]
Hi

This is the error I got when I made my tests, nothing failed when I installed semaphore on the machine instead of the docker container

Thanks
D.

```
01:24:29: Started: 10

01:24:29: access key gitlab_dev_keys installed
01:24:29: Cloning repository
01:24:29: Cloning into 'repository_1'...
01:24:29: Cloning into 'repository_1'...
01:24:30: Host key verification failed.
01:24:30: fatal: Could not read from remote repository.
01:24:30: 
01:24:30: Please make sure you have the correct access rights
01:24:30: and the repository exists.
01:24:30: Failed updating repository: exit status 128
```

**Comment by gcavalcante8808** [comment]
Hello @panda87,

Can you use the following command:

    docker exec -it <CONTAINER> sh -c 'ssh-keyscan -H server >> ~/.ssh/known_hosts'

Where <CONTAINER> is the name of your semaphore container, and 'server' is the address of the gitlab/version control system server that you use.

Try to run the playbook again. If it succeeds, the problem is that the target host fingerprint is not present on known_hosts file. For now, we can just add the information to the README if it works.

**Comment by panda87** [comment]
I can try this, but since I've managed to run the hosts version, I can start my tests.
Later I will try this fix

Thanks!!
D.
